export type TurkceItemType = "letter" | "syllable" | "punctuation" | "word" | "sentence" | "pair";
export type TurkceDifficulty = "easy" | "medium" | "hard";

export type TurkceGameUnitConfig = {
  title: string;
  slug: string;
  description: string;
  instruction: string;
  itemType: TurkceItemType;
  correctItems: string[];
  wrongItems: string[];
  targetWord?: string;
  pointsCorrect: number;
  pointsWrong: number;
  targetCount: number;
  speed: number;
  feedbackSuccess: string;
  feedbackError: string;
  gradeLevels: number[];
  category: string;
  difficulty: TurkceDifficulty;
  isFeatured?: boolean;
  iconEmoji?: string;
};

export const TURKCE_GAME_CATEGORIES = ["Ses Bilgisi", "Sözcükte Anlam", "Dil Bilgisi", "Cümlede Anlam", "Paragraf"] as const;

export const TURKCE_GAMES_CONFIG: TurkceGameUnitConfig[] = [
  {
    title: "Sert Ünsüz Yolu",
    slug: "sert-unsuz-yolu",
    description: "f, s, t, k, ç, ş, h, p harflerini topla.",
    instruction: "Sadece sert ünsüzleri topla.",
    itemType: "letter",
    correctItems: ["f", "s", "t", "k", "ç", "ş", "h", "p"],
    wrongItems: ["a", "e", "o", "u", "b", "m", "y", "z"],
    pointsCorrect: 10,
    pointsWrong: -5,
    targetCount: 20,
    speed: 230,
    feedbackSuccess: "Aferin! Sert ünsüzü yakaladın.",
    feedbackError: "Bu harf sert ünsüz değil.",
    gradeLevels: [5, 6],
    category: "Ses Bilgisi",
    difficulty: "easy",
    isFeatured: true,
    iconEmoji: "🚗",
  },
  {
    title: "Ünlü Harf Avı",
    slug: "unlu-harf-avi",
    description: "Ünlü harfleri seç, puan topla.",
    instruction: "a, e, ı, i, o, ö, u, ü harflerini topla.",
    itemType: "letter",
    correctItems: ["a", "e", "ı", "i", "o", "ö", "u", "ü"],
    wrongItems: ["f", "s", "t", "k", "ç", "ş", "h", "p"],
    pointsCorrect: 10,
    pointsWrong: -5,
    targetCount: 18,
    speed: 215,
    feedbackSuccess: "Ünlü harf doğru!",
    feedbackError: "Bu bir ünsüz harf.",
    gradeLevels: [5],
    category: "Ses Bilgisi",
    difficulty: "easy",
    iconEmoji: "🔤",
  },
  {
    title: "Yumuşak Ünsüz Toplama",
    slug: "yumusak-unsuz-toplama",
    description: "Yumuşak ünsüzleri seçerek ilerle.",
    instruction: "b, c, d, g, ğ harflerini topla.",
    itemType: "letter",
    correctItems: ["b", "c", "d", "g", "ğ"],
    wrongItems: ["p", "ç", "t", "k", "h", "f", "s", "ş"],
    pointsCorrect: 10,
    pointsWrong: -5,
    targetCount: 16,
    speed: 225,
    feedbackSuccess: "Doğru, bu yumuşak ünsüz.",
    feedbackError: "Bu sert ünsüz tarafında.",
    gradeLevels: [5, 6],
    category: "Ses Bilgisi",
    difficulty: "easy",
    iconEmoji: "🧩",
  },
  {
    title: "Hece Toplama",
    slug: "hece-toplama",
    description: "Doğru heceleri toplayıp kelimeyi tamamla.",
    instruction: "Açılan hedef heceyle uyumlu parçaları topla.",
    itemType: "syllable",
    correctItems: ["ka", "le", "mi", "ok", "ul", "ki", "tap"],
    wrongItems: ["zx", "tt", "qq", "öö", "jj"],
    targetWord: "HECE",
    pointsCorrect: 10,
    pointsWrong: -5,
    targetCount: 15,
    speed: 220,
    feedbackSuccess: "Harika hece!",
    feedbackError: "Bu hece uygun değil.",
    gradeLevels: [5, 6],
    category: "Dil Bilgisi",
    difficulty: "medium",
    iconEmoji: "🧱",
  },
  {
    title: "Noktalama Koşusu",
    slug: "noktalama-kosusu",
    description: "Doğru noktalama işaretlerini yakala.",
    instruction: "Hedeflenen noktalama işaretlerini topla.",
    itemType: "punctuation",
    correctItems: [".", "?", "!", ",", ":", ";"],
    wrongItems: ["a", "k", "7", "@", "#"],
    targetWord: "NOKTALAMA",
    pointsCorrect: 10,
    pointsWrong: -5,
    targetCount: 14,
    speed: 235,
    feedbackSuccess: "Noktalama doğru!",
    feedbackError: "Bu işaret uygun değil.",
    gradeLevels: [5, 6, 7],
    category: "Dil Bilgisi",
    difficulty: "medium",
    iconEmoji: "✍️",
  },
  {
    title: "Eş Anlamlı Avı",
    slug: "es-anlamli-avi",
    description: "Eş anlamlı sözcükleri toplayarak ilerle.",
    instruction: "Gösterilen anlama uygun sözcükleri topla.",
    itemType: "word",
    correctItems: ["yürek", "misafir", "cevap", "fakir", "öykü"],
    wrongItems: ["kalem", "masa", "ağaç", "deniz", "dağ"],
    targetWord: "EŞ ANLAM",
    pointsCorrect: 10,
    pointsWrong: -5,
    targetCount: 12,
    speed: 215,
    feedbackSuccess: "Eş anlam doğru!",
    feedbackError: "Bu sözcük eş anlamlı değil.",
    gradeLevels: [6, 7],
    category: "Sözcükte Anlam",
    difficulty: "medium",
    iconEmoji: "🪄",
  },
  {
    title: "Zıt Anlam Köprüsü",
    slug: "zit-anlam-koprusu",
    description: "Zıt anlamlı sözcükleri yakala.",
    instruction: "Hedefin zıt anlamına uygun kelimeleri topla.",
    itemType: "word",
    correctItems: ["uzun-kısa", "genç-yaşlı", "hızlı-yavaş", "sıcak-soğuk"],
    wrongItems: ["masa-sandalye", "elma-armut", "şehir-köy"],
    targetWord: "ZIT ANLAM",
    pointsCorrect: 10,
    pointsWrong: -5,
    targetCount: 10,
    speed: 225,
    feedbackSuccess: "Zıt anlam eşleşti!",
    feedbackError: "Bu zıt anlam değil.",
    gradeLevels: [6, 7],
    category: "Sözcükte Anlam",
    difficulty: "medium",
    iconEmoji: "🌉",
  },
  {
    title: "Yazım Kuralları Görevi",
    slug: "yazim-kurallari-gorevi",
    description: "Doğru yazımları yakalayıp puan kazan.",
    instruction: "Yazım kurallarına uygun sözcükleri topla.",
    itemType: "word",
    correctItems: ["herkes", "birçok", "hiçbir", "değil", "mademki"],
    wrongItems: ["herkez", "bir cok", "hicbir", "deyil", "mademki"],
    pointsCorrect: 10,
    pointsWrong: -5,
    targetCount: 13,
    speed: 240,
    feedbackSuccess: "Yazım doğru!",
    feedbackError: "Bu yazım hatalı.",
    gradeLevels: [6, 7, 8],
    category: "Dil Bilgisi",
    difficulty: "hard",
    iconEmoji: "📝",
  },
  {
    title: "Büyük Ünlü Uyumu Avı",
    slug: "buyuk-unlu-uyumu-avi",
    description: "Büyük ünlü uyumuna uyan kelimeleri bul.",
    instruction: "Büyük ünlü uyumuna uyan kelimeleri topla.",
    itemType: "word",
    correctItems: ["kapı", "çocuk", "kalem", "okul", "yorgan", "bulut"],
    wrongItems: ["anneciğim", "televizyon", "kalori", "otomobil", "şair", "kardeş"],
    pointsCorrect: 10,
    pointsWrong: -5,
    targetCount: 14,
    speed: 220,
    feedbackSuccess: "Uyumlu kelime, harika!",
    feedbackError: "Bu kelime büyük ünlü uyumuna uymuyor.",
    gradeLevels: [5, 6],
    category: "Ses Bilgisi",
    difficulty: "easy",
    isFeatured: true,
    iconEmoji: "🔍",
  },
  {
    title: "Küçük Ünlü Uyumu Avı",
    slug: "kucuk-unlu-uyumu-avi",
    description: "Küçük ünlü uyumu kurallarını eğlenerek öğren.",
    instruction: "Küçük ünlü uyumuna uygun kelimeleri topla.",
    itemType: "word",
    correctItems: ["gözlük", "çocuk", "uygun", "kömür", "yumruk"],
    wrongItems: ["kalori", "tiyatro", "otobüs", "alkolik", "sembol"],
    pointsCorrect: 10,
    pointsWrong: -5,
    targetCount: 14,
    speed: 235,
    feedbackSuccess: "Kural uygun, süper!",
    feedbackError: "Bu kelime küçük ünlü uyumuna uygun değil.",
    gradeLevels: [6, 7],
    category: "Ses Bilgisi",
    difficulty: "medium",
    iconEmoji: "🎯",
  },
  {
    title: "Ünsüz Benzeşmesi Görevi",
    slug: "unsuz-benzesmesi-gorevi",
    description: "Ünsüz benzeşmesi örneklerini toplayıp görev tamamla.",
    instruction: "Ünsüz benzeşmesine uygun örnekleri topla.",
    itemType: "word",
    correctItems: ["kitapçı", "aşçı", "işsiz", "Türkçe", "dişçi"],
    wrongItems: ["kitabcı", "aşcı", "dişci", "işli", "renkde"],
    pointsCorrect: 10,
    pointsWrong: -5,
    targetCount: 13,
    speed: 240,
    feedbackSuccess: "Doğru benzeşme örneği!",
    feedbackError: "Bu örnek benzeşme kuralına uygun değil.",
    gradeLevels: [6, 7],
    category: "Ses Bilgisi",
    difficulty: "medium",
    iconEmoji: "🧠",
  },
  {
    title: "Gerçek Mecaz Terim Koşusu",
    slug: "gercek-mecaz-terim-kosusu",
    description: "Gerçek / mecaz / terim anlam modlarına hazır esnek ünite.",
    instruction: "Gösterilen türe uygun kelimeleri topla.",
    itemType: "word",
    correctItems: ["kapı", "masa", "ayakkabı"],
    wrongItems: ["sıcak bakmak", "ofsayt", "kalbi kırmak"],
    targetWord: "GERÇEK ANLAM",
    pointsCorrect: 10,
    pointsWrong: -5,
    targetCount: 12,
    speed: 230,
    feedbackSuccess: "Tür doğru, devam!",
    feedbackError: "Bu sözcük/ifade hedef türde değil.",
    gradeLevels: [5, 6, 7],
    category: "Sözcükte Anlam",
    difficulty: "medium",
    isFeatured: true,
    iconEmoji: "🏷️",
  },
  {
    title: "Kök Ek Toplama",
    slug: "kok-ek-toplama",
    description: "Kök halindeki sözcükleri seçerek dil bilgisi puanı topla.",
    instruction: "Kök halindeki doğru sözcükleri topla.",
    itemType: "word",
    correctItems: ["göz", "taş", "yaz", "gel", "yol"],
    wrongItems: ["gözlük", "taşlı", "yazmak", "gelince", "yolluk"],
    pointsCorrect: 10,
    pointsWrong: -5,
    targetCount: 12,
    speed: 235,
    feedbackSuccess: "Kök sözcük doğru!",
    feedbackError: "Bu bir ek almış biçim.",
    gradeLevels: [6, 7],
    category: "Dil Bilgisi",
    difficulty: "medium",
    iconEmoji: "🌱",
  },
  {
    title: "Cümlede Anlam Yarışı",
    slug: "cumlede-anlam-yarisi",
    description: "Anlam özelliğine uygun cümle kartlarını yakala.",
    instruction: "Verilen anlam özelliğine uygun cümleleri topla.",
    itemType: "sentence",
    correctItems: [
      "Bu cümlede neden-sonuç ilişkisi vardır.",
      "Koşul anlamı taşıyan ifadeyi seç.",
      "Amaç-sonuç belirten cümleyi topla.",
    ],
    wrongItems: [
      "Özensiz kurulmuş alakasız cümle.",
      "Anlam özelliği taşımayan ifade.",
      "Yanlış anlam ilişkisi örneği.",
    ],
    targetWord: "NEDEN-SONUÇ",
    pointsCorrect: 10,
    pointsWrong: -5,
    targetCount: 10,
    speed: 210,
    feedbackSuccess: "Cümlede anlam doğru!",
    feedbackError: "Bu cümle hedef özelliğe uymuyor.",
    gradeLevels: [7, 8],
    category: "Cümlede Anlam",
    difficulty: "hard",
    iconEmoji: "🧾",
  },
  {
    title: "Paragraf Dedektifi",
    slug: "paragraf-dedektifi",
    description: "Ana fikri destekleyen paragraf kartlarını topla.",
    instruction: "Ana fikri destekleyen doğru ifadeleri topla.",
    itemType: "sentence",
    correctItems: [
      "Parçanın ana düşüncesini doğrudan destekler.",
      "Yazarın savını güçlendiren örnektir.",
      "Ana fikre bağlı yardımcı düşüncedir.",
    ],
    wrongItems: [
      "Konu dışı, ilgisiz bir ayrıntı.",
      "Paragrafla çelişen yorum.",
      "Ana düşünceyle bağlantısı zayıf ifade.",
    ],
    targetWord: "ANA FİKİR",
    pointsCorrect: 10,
    pointsWrong: -5,
    targetCount: 10,
    speed: 205,
    feedbackSuccess: "Paragraf ipucu doğru!",
    feedbackError: "Bu ifade ana fikri desteklemiyor.",
    gradeLevels: [7, 8],
    category: "Paragraf",
    difficulty: "hard",
    isFeatured: true,
    iconEmoji: "🕵️",
  },
];

export function getTurkceGameBySlug(slug: string) {
  return TURKCE_GAMES_CONFIG.find((game) => game.slug === slug);
}
